name: Main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os:
        - macos-latest
        - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - if: ${{ matrix.os == 'ubuntu-latest' }}
      name: Install Linux dependencies
      run: |
        sudo apt install -y libasound2-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxinerama-dev
    - uses: abel0b/setup-premake@v2.3
      with:
        version: "5.0.0-beta2"
    - name: Compile
      run: |
        premake5 gmake2
        make -C build
